### ISSUE TITLE
Refresh throw ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by EranOfer** [goblinfactory/konsole#20]
When ProgressBar defines with text with > console window size.
call to Refresh or Next will throw an exception: count' must be non-negative.\r\nParameter name: count

**Comment by EranOfer** [comment]
Sorry stop working with this project, don't sure how to reproduce the issue.

**Comment by goblinfactory** [comment]
Re-opening this issue - I will manually check this myself later, leaving this open so that I will revisit this during the next update to Konsole.

My guess is this could be a case of the window changing size while some scripts using Konsole are running.

**Comment by goblinfactory** [comment]
@EranOfer instead of closing the issue, you can unsubscribe from notifications.

**Comment by goblinfactory** [comment]
@EranOfer  this is now fixed in latest release, please give that a go. See issue #33  and issue #28 are probably what caused your issue. Those have been fixed. The new `.LockConsoleResizing()` method on Windows is a game changer and makes it so much more practical to build real console applications and utilities.
