### ISSUE TITLE
Incorrect percentage display

### ISSUE THREAD

**Issue by marecki90** [goblinfactory/konsole#26]
Hi, I found percentage display issue. When I create ProgressBarSlim with max as 100:
`var bar = new ProgressBarSlim(100, ProgressWindow);`
and I call 10 times:
`bar.Next("Test");`
I can see the following numbers 0, 1, 2, 3, **5, 5, 7, 7**, 9, 10.

I looked at the code and noticed that the problem is with casting floats that are not written to variables:
![image](https://user-images.githubusercontent.com/11856859/65700119-65820900-e07f-11e9-8d1a-dc36967f8cf6.png)
`Convert.Int32(percentage * 100)` also works if you don't want variables

**Comment by goblinfactory** [comment]
Since you've done 99% of the work, how about submitting a pull request to fix it?
start with a failing acceptance test. 

**Restrictions**
- please note that it does not make any sense that a new ProgressBar representing an activity that has not yet started should have a starting value of 1. 0 is the correct starting value.

So I agree, it looks like there is an issue, however the code example you have provided only shows the issue with your code, and does not show the problem you are suggesting exists with the ProgressBar.

Good luck, it will be a good learning exercise for you. :) and a challenge to 
1) create a good "failing" acceptance test that proves the problem exists
2) create a fix that makes the failing test pass, while keeping all other tests passing.
3) create your first pull request for an open source project. (become a real contributor!) 

regards,
Alan

**Comment by goblinfactory** [comment]
this has been fixed in release 3.4.0, nuget package is now available.
