### ISSUE TITLE
WriteLine conflicts with String.Format

### ISSUE THREAD

**Issue by Tr0sT** [goblinfactory/konsole#40]
`new Window().WriteLine("{json}");` should not throw exception

**Comment by goblinfactory** [comment]
agree, I will fix. Thank you for raising the issue. just finishing up with OpenBox then will get to this.

**Comment by goblinfactory** [comment]
Will be fixed in version 6 because it requires breaking change to the `IWrite` interface, addition of new Write and WriteLine overloads.

Here's the fix : https://github.com/goblinfactory/konsole/compare/master...bugfix-%2340-string-format

I will include this in version 6.

I have enough fun and interesting stuff to include in a 6.x release quite soon, i.e. few days.
Smart Edit, list view and a general cleanup of the API to simplify and make it easier to start using.

**Comment by goblinfactory** [comment]
@Tr0sT  this fixed in version `6.0.0-alpha001`. version 6.0.0 will have some more changes to public API's so please feel free to test this for now if you want.
