### ISSUE TITLE
mdsnippets now has an InPlaceOverwrite option

### ISSUE THREAD

**Issue by SimonCropp** [goblinfactory/konsole#62]
https://github.com/SimonCropp/MarkdownSnippets/#inplaceoverwrite

which mean u dont need to `.source.md` files

let me know if u want a PR that moves over to this convention

**Comment by goblinfactory** [comment]
That's fantastic Simon, ...sorry for taking so long to reply. Yes, please a PR would be excellent, .. I really should do this myself since I was one of the early people to ask for this feature, specifically for Konsole and I've been so caught up in Covid shenanigans I've not had time to do it. 

Having you do a PR would mean you'd show up as a contributor to Konsole, ... which would be fabulous, so if I'm not too late, and that offer still stands, I'd really appreciate it.

If you're also heavily committed totally understand, ping me and let me know and I'll book some time next weekend to do it.
thanks again for the work,
super appreciated
regards, Alan

**Comment by goblinfactory** [comment]
Now using this.

**Comment by SimonCropp** [comment]
damn i completely missed your response. so sorry. in the future, please feel free to hassle me
