### ISSUE TITLE
Itemless based progress

### ISSUE THREAD

**Issue by SamuelEnglard** [goblinfactory/konsole#9]
I have a single task that gives updates over time using a double with rangle 0-1. Showing this is a bit of a pain. I currently pretend to have 10,000 items and just multiply the double by that to get the number of items done. The main issue with this method is the Item X of 10000 show which is invalid. Would be nice to have a mode of showing progress of a single task.

**Comment by goblinfactory** [comment]
very good point. I actually have a fix coming for this,  since I had the same requirement in one of my own dogfood projects, and have an updated progressBar that can be rendered as either a 1 line progress bar (itemless), or a two line progress bar. I'll update this comment when I've checked in the updates to a new progress-bar branch. That branch has significant breaking backward compatible changes so will be a new package and new version number. I won't close this until it's been implemented.

**Comment by goblinfactory** [comment]
This is a quick peek of the new progress bar, copy of the unit test from the branch I'm working on.
This should work for your scenario. Let me know if it doesn't and I'll see if I can update my tests and change before I create the first package.

```csharp

        [Test]
        [TestCase(100,0,   "1234567890 (0  %)          ", "                           ", PbStyle.SingleLine)]
        [TestCase(101,50,  "1234567890 (50 %) ####     ", "                           ", PbStyle.SingleLine)]
        [TestCase(102,100, "1234567890 (100%) #########", "                           ", PbStyle.SingleLine)]
        //[TestCase(103, 0,  "Item     0 of   100. (  0%)", "                           ", PbStyle.DoubeLine)]
        //[TestCase(104, 50, "Item    50 of   100. ( 50%)", "                           ", PbStyle.DoubeLine)]
        //[TestCase(105, 100,"Item   100 of   100. (100%)", "                           ", PbStyle.DoubeLine)]
        public void at_xx_pc_the_progress_bar_should_fill_the_balance_of_the_console_width_pro_ratio(int seq, int i, string line1, string line2, PbStyle style)
        {
            var console = new MockConsole(27,2);
            var pb = new ProgressBar(console, 100, 10);
            pb.Refresh(i,"1234567890");
            var expected = new string[]
            {
                line1,
                line2
            };
            Console.WriteLine(console.BufferWrittenString);
            CollectionAssert.AreEqual(expected,console.Buffer);
        }
```

**Comment by SamuelEnglard** [comment]
So by setting `PbStyle.SingleLine` I'll get what I'm looking for?

**Comment by goblinfactory** [comment]
When I publish the updated package `ProgressBar` will not be backward compatible, i.e. it will be a breaking change. The new PB will default to itemless, and you'll need to pass in `PbStyle.DoubeLine` to get the old behavior. The new PB will work exactly as you requested.
:)

**Comment by goblinfactory** [comment]
I've published package `3.0.1` which contains the new ProgressBar, it's beta, only because the old two line behaviour is still being finished, tests and a few last minute changes. The new itemless default behaviour won't change, so that's stable.  To get the new itemless PB simply run 

>update-package Konsole

I'll be working on and off `Konsole`  for the next few days as I'm using it quite heavily myself on another project so drop me a line if you have any problems, I can get fixes out quite quickly.

cheers, 

Alan

**Comment by goblinfactory** [comment]
(I'll leave this issue open for a while to give you a chance to review, let me know when you're happy and I'll close it. If I don't hear from you in a few days I'll close it, you can always DM me if you have any issues.)

**Comment by SamuelEnglard** [comment]
Works beautifully! Thanks!
